version: '3.9'
services:
  adminer:
    container_name: keycloak-workshop-adminer
    image: adminer
    ports:
      - '20080:8080'
  maildev:
    container_name: keycloak-workshop-maildev
    image: 'djfarrelly/maildev:latest'
    ports:
      - '20081:80'
      - '20082:25'
  postgres:
    container_name: keycloak-workshop-postgres
    image: postgres
    volumes:
      - postgres_workshop_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - '20083:5432'
  keycloak:
    container_name: keycloak-workshop-keycloak
    image: quay.io/keycloak/keycloak
    command: ["--verbose", "start-dev", "--http-port=11100"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
      KC_FEATURES: linkedin-oauth
      KC_FEATURES_DISABLED: impersonation
    ports:
      - '20090:11100'
      - '20091:8443'
    depends_on:
      - postgres
volumes:
  postgres_workshop_data:
    driver: local
  ignore: null
